steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/circlesave/circlesave:latest', '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/circlesave/circlesave:$COMMIT_SHA', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/circlesave/circlesave:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/circlesave/circlesave:$COMMIT_SHA']

 - name: 'gcr.io/://google.com'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'circlesave',
      '--image', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/circlesave/circlesave:$COMMIT_SHA',
      '--platform', 'managed',
      '--region', 'asia-southeast1',
      '--allow-unauthenticated'
    ]

images:
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/circlesave/circlesave:latest'
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/circlesave/circlesave:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
